### ISSUE TITLE
Could not resolve a service 

### ISSUE THREAD

**Issue by Oracularman** [DevelAx/Asp.Net-MVC-Core-2.0-Identity#1]
get the following error 

"Could not resolve a service of type 'MvcProject.Repository.IDbInitializer' for the parameter 'dbInitializer' of method 'Configure' on type 'MvcProject.Startup'

**Comment by Oracularman** [comment]
Resolved. Here is my startup.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using MvcProject.Models;
using MvcProject.Data;
using MvcProject.Services;
using MvcProject.Core;
using MvcProject.Core.Helpers;
using MvcProject.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.Authorization;
using MvcProject.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;

namespace MvcProject
{
    public class Startup
    {
        public IConfiguration Configuration { get; set; }

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
          services.AddDbContext<MvcProjectDbContext>(options => options.UseSqlite("Data Source=MvcProjectB.db"));
           
                services.AddIdentity<PROJECTUser, IdentityRole>(config =>
                {
                    config.SignIn.RequireConfirmedEmail = true;
                })
             .AddEntityFrameworkStores<MvcProjectDbContext>()
             .AddDefaultTokenProviders();


            services.Configure<IdentityOptions>(options =>
            {
                // Password settings
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 8;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;
                options.Password.RequireLowercase = false;
                options.Password.RequiredUniqueChars = 6;

                // Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);
                options.Lockout.MaxFailedAccessAttempts = 10;
                options.Lockout.AllowedForNewUsers = true;

                // User settings
                options.User.RequireUniqueEmail = true;
            });

            services.ConfigureApplicationCookie(options =>
            {
                // Cookie settings
                options.Cookie.HttpOnly = true;
                options.Cookie.Expiration = TimeSpan.FromDays(150);
                options.LoginPath = "/Account/Login"; // If the LoginPath is not set here, ASP.NET Core will default to /Account/Login
                options.LogoutPath = "/Account/Logout"; // If the LogoutPath is not set here, ASP.NET Core will default to /Account/Logout
                options.AccessDeniedPath = "/Account/AccessDenied"; // If the AccessDeniedPath is not set here, ASP.NET Core will default to /Account/AccessDenied
                options.SlidingExpiration = true;
            });

            //Authorization handlers.
            services.AddScoped<IAuthorizationHandler,
                                  PROJECTIsOwnerAuthorizationHandler>();

            services.AddSingleton<IAuthorizationHandler,
                                  PROJECTAdministratorsAuthorizationHandler>();

            services.AddSingleton<IAuthorizationHandler,
                                  PROJECTAuthorizationHandler>();


            services.AddSingleton<IEmailSender, EmailSender>();

            services.AddMvc();
           
            services.Configure<AuthMessageSenderOptions>(Configuration);

            services.AddScoped<IDbInitializer, DbInitializer>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseAuthentication();

       
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}

**Comment by develax** [comment]
Ok, but I couldn't understand why the error occurred and what you did in particular to resolve it. I checked it and it was built without errors on my side.
